### ISSUE TITLE
bug in ESP32_ble_UART/main/ble_uart_server.c

### ISSUE THREAD

**Issue by ujeenator** [pcbreflux/espressif#25]
File:
espressif/esp32/app/ESP32_ble_UART/main/ble_uart_server.c

Function: 
descr2_read_handler

Line:
258:	if (gl_char[0].descr_val!=NULL) {

It check 0 index characteristic for, but should check 1 index 

Correct:
258:	if (gl_char[1].descr_val!=NULL) {

**Comment by pcbreflux** [comment]
Thanks for finding the bug, changed the index from 0 to 1.
